lb-jenkins:
  ports:
  - 8888:8080
  tty: true
  image: rancher/load-balancer-service
  links:
  - jenkins:jenkins
  stdin_open: true

jenkins:
  labels:
    io.rancher.sidekicks: jenkins-data
    backup_folder: /var/jenkins_home
  tty: true
  image: jenkins:2.19.1
  volumes_from:
  - jenkins-data
  stdin_open: true

jenkins-data:
  labels:
    io.rancher.container.start_once: 'true'
  entrypoint:
  - /bin/true
  image: jenkins:2.19.1
  volumes:
  - /var/jenkins_home

jenkins-builder:
  image: rancher/external-service
